課題1＆2
sugisawakaito/task pull request #1
Opened 2020-12-16 06:31 UTC by sugisawakaito

2020-12-16 09:43 UTC, masanarih0ri requested changes
コメントしました。ご確認をお願いいたします。また、テストが無いようなので作ってみましょう。

2020-12-16 09:43 UTC, masanarih0ri commented on app/views/layouts/_header.html.erb
> +	<div class="topBar">
こちらのファイルのインデントがずれています。

2020-12-16 09:43 UTC, masanarih0ri commented on app/views/layouts/application.html.erb
> +      <%= yield :inline_js %>
こちらは必要でしょうか？

2020-12-16 09:43 UTC, masanarih0ri commented on app/views/potepan/products/_about.html.erb
> +<%# <div class="tabArea">
コメントアウトのみのファイルを置いているのはなぜでしょうか？

2020-12-16 09:43 UTC, masanarih0ri commented on app/views/potepan/products/_detail_products.html.erb
> +  <h2><%= @product.name %></h2>
partialファイルの中でインスタンス変数を使わないようにしましょう。

2020-12-16 09:43 UTC, masanarih0ri commented on app/views/potepan/products/_production.html.erb
> +       <h5>Scarf Ring Corner</h5>
h5,h3タグのインデントがずれているようです。

2020-12-16 09:43 UTC, masanarih0ri commented on app/helpers/application_helper.rb
> +    if page_title.empty?
emptyではなく別のメソッドのほうがいい気がします。

2020-12-16 09:43 UTC, masanarih0ri commented on app/helpers/application_helper.rb
> +      page_title + " | " + base_title
変数展開使ってみてはどうでしょうか？

2020-12-16 09:43 UTC, masanarih0ri commented on app/views/layouts/_footer.html.erb
> +          <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
nowでも動きますが別のメソッドの方が適切だと思うので探してみてください。

2020-12-16 10:52 UTC, sugisawakaito commented on app/views/layouts/_header.html.erb
> +	<div class="topBar">
直しました。

2020-12-16 10:52 UTC, sugisawakaito commented on app/views/layouts/application.html.erb
> +      <%= yield :inline_js %>
javascript_include_tag を最後に持ってくることで、htmlの読み込むスピードを上げる狙いです。
また、 <%= yield :inline_js %>　は必要ではなかったので削除しました。

2020-12-16 10:52 UTC, sugisawakaito commented on app/views/potepan/products/_about.html.erb
> +<%# <div class="tabArea">
parshalから外しました。

2020-12-16 10:52 UTC, sugisawakaito commented on app/views/potepan/products/_detail_products.html.erb
> +  <h2><%= @product.name %></h2>
直しました。

2020-12-16 10:52 UTC, sugisawakaito commented on app/views/potepan/products/_production.html.erb
> +       <h5>Scarf Ring Corner</h5>
直しました。

2020-12-16 10:52 UTC, sugisawakaito commented on app/helpers/application_helper.rb
> +    if page_title.empty?
emptyメソッドではなく、nilメソッドも合わせて実行できるblankメソッドを採用しました。

2020-12-16 10:53 UTC, sugisawakaito commented on app/helpers/application_helper.rb
> +      page_title + " | " + base_title
変数展開について調べましたが、あまり出てこなかったので、base_titleだけ変数として使えるようにしました。

2020-12-16 10:53 UTC, sugisawakaito commented on app/views/layouts/_footer.html.erb
> +          <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
config/application.rb を参照して実行する、currentメソッドに変更しました。

2020-12-16 10:54 UTC, sugisawakaito reviewed
rspecですが、学習が追いついておらず、初期に作れるものしかありませんよろしくお願いします。

2020-12-16 11:44 UTC, toda-potepan reviewed
お疲れ様です。

まず2点あります
* PRを提出する際にはデプロイされたアプリが見れる、herokuのURLを提出するようにお願いします。
* 今回実装されたhelperメソッドやcontrollerに対するrspecは必須要件なので、どのようなテストを追加するべきか考えながら追加をお願いします。

その他、いくつかコメントしたので合わせて確認をお願いします。

2020-12-16 11:44 UTC, toda-potepan commented on app/helpers/application_helper.rb
> +    base_title = "potepanec"
こちらは定数化しましょう

2020-12-16 11:44 UTC, toda-potepan commented on app/helpers/application_helper.rb
> +      "page_title +  |  + #{base_title}"
`+` は必要そうでしょうか？

2020-12-16 11:44 UTC, toda-potepan commented on app/views/layouts/_footer.html.erb
> +<!-- LOGIN MODAL -->
LOGINとSIGN UP のMODALは厳密にはFooterの要素ではないので別のファイルに切り出しましょう

2020-12-16 11:44 UTC, toda-potepan commented on app/views/layouts/_header.html.erb
> +	<div class="topBar">
まだインデントが修正されていないようです。
他のファイルと同様にインデントは半角スペース2つにしましょう。

2020-12-16 11:44 UTC, toda-potepan commented on app/views/layouts/_header.html.erb
> +				<a class="navbar-brand" href="index.html"><%= image_tag("img/logo.png", :alt => "") %></a>
こちらもlink_toに書き換えましょう

2020-12-16 11:44 UTC, toda-potepan commented on app/views/potepan/products/show.html.erb
> +<% provide(:title,  " Products") %>
これですとどの商品ページでも `Products` になってしまうので、表示している商品の名前を入れるようにしましょう。

2020-12-16 11:44 UTC, toda-potepan commented on app/views/potepan/products/show.html.erb
> +              </div>   %>
もしこの辺りのコードが不要であれば、コメントアウトではなく削除しましょう

2020-12-16 13:49 UTC, toda-potepan reviewed
お疲れ様です。

先程お伝えした下記の内容が対応されていない様だったのでご確認の方お願いします。
```
helperメソッドやcontrollerに対するrspecは必須要件なので、どのようなテストを追加するべきか考えながら追加をお願いします。
```

その他、いくつかコメントしたので合わせて確認をお願いします。

2020-12-16 13:49 UTC, toda-potepan commented on config/routes.rb
> +    get 'product_grid_left_sidebar',to: 'sample#product_grid_left_sidebar'
こちらは元のコードで良かった様に見えるのですが、変更された意図は何でしょうか？

2020-12-16 13:49 UTC, toda-potepan commented on config/initializers/constants.rb
> +module PAGE_TITLE
`PAGE_TITLE` -> `Constants` のほうが良いと思います

2020-12-16 13:49 UTC, toda-potepan commented on app/helpers/application_helper.rb
> +      page_title + " | " + PAGE_TITLE::BASE_TITLE
元々書いて頂いていた下記の方法で式展開出来ているのですが
> "page_title +  |  + #{base_title}"

式展開の場合は間に `+` 挟む必要はないので不要ではありませんか？というのでコメントしました。

今回の修正により式展開ではなくなってしまっているので、再度ご確認お願いします。

2020-12-16 13:56 UTC, sugisawakaito commented on app/helpers/application_helper.rb
> +    base_title = "potepanec"
こちらは、定数化したmoduleをconfig/initializers/constants.rbを新しく作成し、full_titleメソッドで使えるようにしました。

2020-12-16 13:56 UTC, sugisawakaito commented on app/views/layouts/_footer.html.erb
> +<!-- LOGIN MODAL -->
footerのパーシャルからloginとsignupの部分を抜き出してパーシャル化し、読み込むようにしました。

2020-12-16 13:56 UTC, sugisawakaito commented on app/views/layouts/_header.html.erb
> +				<a class="navbar-brand" href="index.html"><%= image_tag("img/logo.png", :alt => "") %></a>
hrefの部分を、/potepan　に書き換え、ホーム画面に戻るようにしました。

2020-12-16 13:56 UTC, sugisawakaito commented on app/views/potepan/products/show.html.erb
> +<% provide(:title,  " Products") %>
titleに、"#{@products.name}を表示するようにしました。

2020-12-16 13:56 UTC, sugisawakaito commented on app/views/potepan/products/show.html.erb
> +              </div>   %>
削除しました。

2020-12-17 07:12 UTC, sugisawakaito commented on app/helpers/application_helper.rb
> +      page_title + " | " + PAGE_TITLE::BASE_TITLE
ここは、+ を外しました。

2020-12-17 07:12 UTC, sugisawakaito commented on config/initializers/constants.rb
> +module PAGE_TITLE
こちらは試してみましたが、エラーが出てしまったのでそのままにしています。

2020-12-17 07:12 UTC, sugisawakaito commented on config/routes.rb
> +    get 'product_grid_left_sidebar',to: 'sample#product_grid_left_sidebar'
戻しました。

2020-12-17 12:20 UTC, nakanoTaku commented on app/controllers/potepan/products_controller.rb
> +    @product = Spree::Product.find(params[:id]).master
.masterって必要でしょうか？

2020-12-17 12:23 UTC, nakanoTaku commented on app/helpers/application_helper.rb
> +      page_title + " | " + PAGE_TITLE::BASE_TITLE
式展開する形で書きましょう。
「ruby 式展開」でググれば色々出てくると思いますので、調べて見てください。

2020-12-17 12:24 UTC, nakanoTaku commented on app/views/layouts/_header.html.erb
> +	<div class="topBar">
こちら再度インデントの確認お願いします。

2020-12-17 12:25 UTC, nakanoTaku commented on app/views/potepan/products/show.html.erb
> +<% provide(:title,  "#{@product.name}") %>
半角スペースが1つ余分に入ってしまってますね。

2020-12-17 12:26 UTC, nakanoTaku commented on config/environments/production.rb
> +    bucket: 'potepanec2-submit'
access_key_id、secret_access_key以外も環境変数にしましょう。

2020-12-17 12:28 UTC, nakanoTaku commented
コメントしました。ご確認をお願いいたします。

2020-12-17 13:01 UTC, sugisawakaito commented on app/views/potepan/products/show.html.erb
> +<% provide(:title,  "#{@product.name}") %>
直しました。

2020-12-17 13:01 UTC, sugisawakaito commented on config/environments/production.rb
> +    bucket: 'potepanec2-submit'
S3_REGION,BUCKET_NAME,HOST_NAME を新たに作成しました。

2020-12-18 12:59 UTC, masanarih0ri requested changes
いくつかコメントしました。
前回のレビューから見て修正できていない箇所もいくつかありましたので、ご確認ください。また、コミットメッセージが実装内容と違うケースが散見されましたので、次回以降はできるだけコミットメッセージも内容に合わせるようにしてください。
例：テストを新しく書き加えた場合 -> xxのためrspecのテストを追加する
くらいのコミットメッセージは書いた方がいいと思います。

2020-12-18 12:59 UTC, masanarih0ri commented on app/helpers/application_helper.rb
> +      page_title + " | " + PAGE_TITLE::BASE_TITLE
これって式展開の形に直せていますか？
？ `#{}` を使った形で書き直してみましょう。

2020-12-18 12:59 UTC, masanarih0ri commented on app/views/layouts/_footer.html.erb
> +    <div class="container">
ここの箇所は半角スペース2つ以上のインデントが空いていると思います。HTMLのファイルは全て見直してみましょう。

2020-12-18 12:59 UTC, masanarih0ri commented on app/views/layouts/_header.html.erb
> +	<div class="topBar">
こちらもインデントずれたままになっていると思います。
インデントがぐちゃぐちゃでも動作には関係ないですが、インデントがぐちゃぐちゃのファイルがマージされるのは私は経験したことがないので、直しましょう！

2020-12-18 12:59 UTC, masanarih0ri commented on spec/helpers/application_helper_spec.rb
> +      end
nilが渡ってきたケースもテストしてみましょう。

2020-12-18 14:41 UTC, sugisawakaito commented
前回のプッシュと比べて変更されていない原因は、過去のpushに戻るタイミングがあり、その時に変更が戻されたことに気づけなかったことだと思います。
また、自分のエディタではパーシャルのインデントは整っていたので、崩れていることに気づきませんでした。
しっかりPRを確認しようと思います。

2020-12-18 14:47 UTC, sugisawakaito commented on spec/helpers/application_helper_spec.rb
> +      end
このもうひとつ上のcontextでnillのパターンも検証できているつもりですが、いかがですか？
ご確認お願いします。

2020-12-18 23:55 UTC, kaizumoto commented on .rspec
> +--require spec_helper
format documentationすると見やすくなります。

2020-12-18 23:55 UTC, kaizumoto commented on .rubocop_airbnb.yml
> +    - rubocop-airbnb
改行コードがおかしいので修正してください。

2020-12-18 23:56 UTC, kaizumoto commented on app/helpers/application_helper.rb
> +    base_title = "potepanec"
定数に切ったのであれば、定数を使いましょう。

2020-12-18 23:57 UTC, kaizumoto commented on app/views/layouts/_footer.html.erb
> +</div>
改行コードがおかしいです。
他のファイルも直してください。

2020-12-18 23:57 UTC, kaizumoto commented on app/views/layouts/_header.html.erb
> +                <form  id="form01" action="product-grid-left-sidebar.html" method="post">
元からだと思いますがformの後のスペースが多いです。

2020-12-18 23:58 UTC, kaizumoto commented on app/views/layouts/_header.html.erb
> +          <li><%= link_to "HOME" , "/potepan" %></li>
"HOME" ,間に入っているスペースは消してください。

2020-12-18 23:58 UTC, kaizumoto commented on app/views/layouts/application.html.erb
> +      <%= stylesheet_link_tag    'application', media: 'all' %>
stylesheet_link_tag    '
間にはいっているスペースは半角スペース1つにしましょう。

2020-12-18 23:59 UTC, kaizumoto commented on app/views/potepan/products/show.html.erb
> +<% provide(:title, "#{@product.name}") %>
文字列の式展開にする必要はないかと思います。

2020-12-19 00:00 UTC, kaizumoto commented on app/views/potepan/products/show.html.erb
> +  </section>
partialに切り出しましょう。

2020-12-19 00:00 UTC, kaizumoto commented on app/views/potepan/products/show.html.erb
> +                  <%# <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li>  %>
不要なら削除しましょう。

2020-12-19 00:01 UTC, kaizumoto commented on config/initializers/constants.rb
> +    BASE_TITLE = 'potepanec'
L.3もそうですがインデントがおかしいです。
freezeしてください。

2020-12-19 00:01 UTC, kaizumoto commented on spec/factories/tests.rb
> +FactoryBot.define do
使ってないようなので削除しましょう。

2020-12-19 00:02 UTC, kaizumoto commented on docker-compose.yml
> +      # 以下の行をコメントアウトしています
このコメントは意味のないコメントなので削除しましょう。
コメントアウトしているのは見ればわかるので、コメントするときは意図がわかりづらい時に補足として記載するようにしましょう。

2020-12-19 00:03 UTC, kaizumoto commented on spec/features/products_spec.rb
> +require 'rails_helper'
ファイル毎に読み込むのではなく事前に読み込みましょう。
`.rspec`にかけます。

2020-12-19 00:05 UTC, kaizumoto commented
レビュアーの伊豆本です。
インラインでコメントしましたのでご確認ください。
またプルリクの説明は仕様や工夫した点を記載するようにしましょう。
コミットメッセージも何のためのコミットなのかわかるように記載してください。
`change gem`とかだとgemfileを変更しているのは差分を見ればわかります。なぜ変更したのかを記載するようにしましょう。

2020-12-19 10:30 UTC, return-nil requested changes
レビュアーの仲井です。
インラインでコメントしましたのでご確認ください。
またdescriptionにはPRの内容を書いたほうが良い気がします。

2020-12-19 10:30 UTC, return-nil commented on .rubocop.yml
> +  - 'config/routes.rb'
`config/routes.rb`は対象外にしないほうが良い気がしました。

2020-12-19 10:30 UTC, return-nil commented on .rubocop.yml
> +  - 'config/initializers/devise.rb'
config/environments、config/initializers/ 配下は以下のようにまとめて指定しても良い気がしました。
```
- "config/environments/*"
- "config/initializers/*"
```

2020-12-19 10:30 UTC, return-nil commented on .rubocop.yml
> +  - 'app/helpers/application_helper.rb'
以下のファイルも対象外にしないほうが良い気がしました。
```
  - 'app/helpers/application_helper.rb'
  - 'app/models/spree_products.rb'
```

2020-12-19 10:30 UTC, return-nil commented on .rubocop_todo.yml
> +  Max: 920
このあたりの設定値はどのように決められましたでしょうか？
設定がすごくゆるい気がしています。

2020-12-19 10:30 UTC, return-nil commented on app/helpers/application_helper.rb
> +    base_title = "potepanec"
こちらの対応がされていないようです。

2020-12-19 10:30 UTC, return-nil commented on app/views/layouts/_header.html.erb
> +          <li><%= link_to "HOME", "/potepan" %></li>
こちらヘルパーメソッドを使いましょう。

2020-12-19 10:30 UTC, return-nil commented on app/views/layouts/application.html.erb
> +  <html>
インデントがおかしい気がします。

2020-12-19 10:30 UTC, return-nil commented on app/views/potepan/products/_light_section.html.erb
> +            <a href="/potepan">Home</a>
こちらもヘルパーメソッドを使いましょう。

2020-12-19 10:30 UTC, return-nil commented on app/views/potepan/products/show.html.erb
> +  <%= render 'light_section', product: @product %>
インデントがおかしいですかね？

2020-12-19 10:30 UTC, return-nil commented on spec/helpers/application_helper_spec.rb
> +      end
引数のデフォルト値に空文字を設定してあるので`nil`の場合の検証は出来ていない気がします。

2020-12-19 13:19 UTC, return-nil commented
rubocopの設定での修正箇所が多いかつコミットメッセージが適切ではないためレビューがしずらいです。
対応漏れもあるのでコミットを適切な単位で行いコミットメッセージもその修正が分かるものにして下さい。
インラインでコメントしてある箇所にはどのコミットで修正したか分かるようにコミットハッシュと一緒に修正した旨を返信してほしいです。

2020-12-21 12:18 UTC, nakanoTaku commented on app/views/layouts/_header.html.erb
> +          <li><%= link_to "/potepan" do %>Home<%end%></li>
link_toの使い方を調べて見ましょう。テキストをタグの外にする必要はないです。

2020-12-21 12:19 UTC, nakanoTaku commented on app/views/potepan/products/_light_section.html.erb
> +          <%end%>
上と同様です。

2020-12-21 12:27 UTC, nakanoTaku commented
レビュアの中野です。
インラインでコメントしましたので、ご確認お願いします。

2020-12-21 23:16 UTC, kaizumoto commented on .rspec
> +--format documentation
改行コードかEOFがおかしくなっているので修正してください。

2020-12-21 23:17 UTC, kaizumoto commented on .rubocop_airbnb.yml
> +  - rubocop-airbnb
こちらもEOFがおかしくなっていそうです。

2020-12-21 23:18 UTC, kaizumoto commented on app/helpers/application_helper.rb
> +      "#{Constants::TITLE}"
文字列を結合しているわけではないので、`Constants::TITLE`のみで大丈夫です。

2020-12-21 23:20 UTC, kaizumoto commented on config/initializers/constants.rb
> +  TITLE = 'potepanec'
freezeしましょう。

2020-12-21 23:22 UTC, kaizumoto commented
レビュアーの伊豆本です。
インラインでコメントしましたのでご確認ください。
EOFがおかしくなっているファイルが複数あったので、課題を提出する前にセルフチェックするようにしましょう。

2020-12-22 12:25 UTC, toda-potepan commented on app/views/layouts/_header.html.erb
> +        <a class="navbar-brand" href='/potepan' ><%= image_tag("img/logo.png") %></a>
こちらもlink_toの形で記述するようにしましょう

2020-12-22 12:25 UTC, toda-potepan commented on app/views/potepan/products/_production.html.erb
> +<div class="row productsContent">
`production` というファイル名は適切ではないので別名にしましょう
（プログラミングの世界においてproductionとは本番環境を指すことが多いです）

2020-12-22 12:25 UTC, toda-potepan commented on spec/requests/products_request_spec.rb
> +RSpec.describe Potepan::ProductsController, type: :controller do
商品に関するテストケースもあると良いと思います

2020-12-22 12:25 UTC, toda-potepan commented on .rubocop.yml
> +  - 'app/helpers/application_helper.rb'
こちらの内容が対応されていないようなので確認をお願いします。

2020-12-22 12:25 UTC, toda-potepan commented
お疲れ様です、レビュアーの戸田です。
インラインでコメントしましたので確認よろしくお願いします。

2020-12-22 14:54 UTC, toda-potepan reviewed
お疲れ様です、レビュアの戸田です。
コメントをしたので確認の方よろしくお願いします。

2020-12-22 14:54 UTC, toda-potepan commented on .rubocop.yml
> +  - 'app/helpers/application_helper.rb'
まだ `- 'app/helpers/application_helper.rb'` が含まれているようです

2020-12-22 14:54 UTC, toda-potepan commented on app/views/layouts/_header.html.erb
> +          <li><%= link_to 'Home', "/potepan" %></li>
名前付きルートの書き方(_path）で遷移先を指定出来ると良いです
(他の箇所も合わせて修正をお願いします)

2020-12-22 14:54 UTC, toda-potepan commented on spec/requests/products_request_spec.rb
> +RSpec.describe Potepan::ProductsController, type: :controller do
ディレクトリが `requests` なのに対して、実装されているテスト内容が `controller` になっているようです。

2020-12-22 14:54 UTC, toda-potepan commented on spec/helpers/application_helper_spec.rb
> +      it "removes symbol" do
`removes symbol` だとこのテストがどの様な結果を期待値としているかが明確ではありません。
誰が見てもどの様な結果を期待しているのかがわかるような内容にしましょう。

2020-12-23 09:09 UTC, masanarih0ri commented on app/views/layouts/_header.html.erb
> +
細かいのですが、ここの空行は要らないと思います。

2020-12-23 09:14 UTC, masanarih0ri reviewed
少しコメントしました。あと少しなので頑張ってください！

2020-12-23 12:11 UTC, tsakamo71 commented on .rubocop.yml
> +  - .rubocop_todo.yml
todoは残さず処理しましょう。
そしてこのtodoは不要ですので削除してください。

2020-12-23 12:13 UTC, tsakamo71 commented on .rubocop.yml
> +  # application_helper.rb はrspecとの兼ね合いで除外しています。
除外してはいけません。
何か理由があれば詳しく説明を要します。

2020-12-23 12:15 UTC, tsakamo71 commented on .rubocop_todo.yml
> +# This configuration was generated by
このファイルは不要です。
特段の理由がない限りTodoを残してはいけません。

2020-12-23 12:18 UTC, tsakamo71 commented on app/views/potepan/products/_media_left.html.erb
> +      <% product.images.each_with_index do |image, i| %>
[IMO]
iという変数名は慣習でカウンタを意味するので、この場合は不適切です。
imgとかが良いでしょう。

2020-12-23 12:27 UTC, tsakamo71 commented on spec/controller/products_controller_spec.rb
> +    scenario "responds successfully" do
scenarioではなくitのほうが適切です。

2020-12-23 12:35 UTC, tsakamo71 commented
レビュアーの坂本です。
db/migrateは変更する必要がありませんが、多数変更がされているようで気になります。
airbnbを設定し忘れてrubocopの検査をしたたきに変更したときの状況と同じように思います。
もしそうなら、初期の状態に戻す事をお勧めします。
修正の必要がないものを変更してしまうのはご法度です。

その他コメントしましたので確認をお願いします。

2020-12-23 17:21 UTC, sugisawakaito commented
application_helper.rb をrubocop.ymlとrsepとの兼ね合いから外してます。
application_helper.rb　にrubocopを通すと　def full_title(page_title: '')に変更するようにエラーがでます。が、そこを変更すると、次にrspecによってエラーが出ます。
なので、大きな問題はないと判断して、rubocop.ymlに記述しています。
また、db/migrateに関しては、rubocopのエラーに対して対応しました。

2020-12-24 14:44 UTC, kaizumoto commented on config/initializers/constants.rb
> +end
EOFがおかしいです。

2020-12-24 14:45 UTC, kaizumoto commented on spec/helpers/application_helper_spec.rb
> +end
EOFがおかしいです。エディタの設定を見直してみてはいかがでしょうか？

2020-12-24 14:48 UTC, kaizumoto commented
レビュアーの伊豆本です。
概ね問題ないかと思います。EOFについてコメントしていますのでご確認ください。
また、application_helperを対象外にしているということですが、テストが通らないので除外したというのは理解できなかったです。
application_helperを対象外にするのではなく、rubocopの設定を変更するのであればまだわかります。
application_helperを対象外にせず対応をお願いします。

2020-12-24 16:28 UTC, masanarih0ri commented on spec/features/products_spec.rb
> +
こちらのspecファイルは書き途中のような感じですが、どうでしょうか？
https://qiita.com/jnchito/items/607f956263c38a5fec24
こちらの記事など参考にして、ページ遷移した後にproductの商品名や価格などの表示がされているかをチェックするなどしてみてはいかがでしょう？

2020-12-24 16:35 UTC, masanarih0ri commented
少しコメントさせていただきました。ご確認よろしくお願いいたします。

2020-12-24 16:35 UTC, masanarih0ri approved these changes

2020-12-24 23:34 UTC, kaizumoto commented on spec/rails_helper.rb
> +require 'spec_helper'
`.rspec`で`rails_helper`を読み込んでいるので不要かと思います。

2020-12-24 23:36 UTC, kaizumoto commented
レビュアーの伊豆本です。
1点細かい点をコメントしました。
もう少しだと思うので頑張りましょう。

2020-12-25 12:26 UTC, nakanoTaku commented on app/views/potepan/products/_light_section.html.erb
> +          <%= link_to 'Home', potepan_path %>
細かいですが、スペース追加しましょう。

2020-12-25 12:33 UTC, nakanoTaku commented
レビュアーの中野です。
1点インデントが気になりましたので、コメントさせていただきました。
が、他問題ないと思いますのでLGTMです。
修正しておいてください！

2020-12-25 14:45 UTC, masanarih0ri commented
お疲れ様です。私からもLGTMです。中野さんのおっしゃっているインデントの部分だけ直してからマージをお願いいたします。

2020-12-25 17:33 UTC, merged