task 3
sugisawakaito/task pull request #2
Opened 2020-12-25 18:23 UTC by sugisawakaito

2020-12-26 03:07 UTC, MasanariChikamatsu requested changes
レビュアの近松です。
コメントしたのでご確認をお願いします

2020-12-26 03:07 UTC, MasanariChikamatsu commented on app/views/potepan/categories/_category.html.erb
> +              <ul id="taxonomy-<%= taxonomy.id %>" class="collapse collapseItem">
ここインデント設ける必要ないのでは？

2020-12-26 03:07 UTC, MasanariChikamatsu commented on app/views/potepan/categories/_light_section.html.erb
> +            <a href="/potepan">Home</a>
`/potepan` の部分、URLHelperを使いましょう

2020-12-26 03:07 UTC, MasanariChikamatsu commented on app/views/potepan/categories/_light_section.html.erb
> +            <a href="/potepan">Home</a>
`link_to` を使いましょう

2020-12-26 03:07 UTC, MasanariChikamatsu commented on spec/features/categories_spec.rb
> +        expect(page).to have_content taxonomy.name
`taxonomy.name` の値って文字列で　”Category"　ですよね？
ベタがきの方がテストとしては意味あるものになると思います

2020-12-26 10:21 UTC, return-nil requested changes
レビュアーの仲井です。
インラインでコメントしましたのでご確認下さい。
また、以下内容のご確認もお願いします。
- 商品画像や価格をクリックした際に商品詳細ページへ遷移しないようなので遷移できるようにした方が良いかもしれません。
- 商品詳細ページの`一覧ページへ戻る`リンクが機能していないようです。
- PRのdescriptionが書かれていないので書くクセをつけましょう。

2020-12-26 10:21 UTC, return-nil commented on app/views/potepan/categories/_light_section.html.erb
> +            <a><% link_to "Home",  potepan_path %></a>
細かいですがカンマの後にスペースが2つありますかね？

2020-12-26 10:21 UTC, return-nil commented on spec/features/categories_spec.rb
> +    it "display correct categories page" do
カテゴリ毎に個数を表示するようになっていると思うのでそこの表示のテストがあっても良い気がしました。
また、商品をクリックした際に商品詳細ページに遷移するテストがあっても良い気がします。

2020-12-26 10:21 UTC, return-nil commented on spec/features/categories_spec.rb
> +RSpec.feature "Categories", type: :feature do
このファイルではないのですが商品詳細ページのテストに`一覧ページへ戻る`リンクのテストがあっても良い気がしました。

2020-12-26 14:13 UTC, sugisawakaito commented
おそらくdescriptionとtitleが同じ行で設定されています。
次回から改善しようと思います。よろしくお願いします。

2020-12-27 00:07 UTC, kaizumoto commented on app/views/potepan/categories/_single_product.html.erb
> +          <%= link_to potepan_product_path(product.id) do %>
以降のインデントがずれています。

2020-12-27 00:08 UTC, kaizumoto commented on spec/controller/categories_controller_spec.rb
> +      expect(assigns(:taxon)).to eq(taxon_child)
他にもインスタンス変数があるので検証しましょう。

2020-12-27 00:08 UTC, kaizumoto commented on spec/controller/categories_controller_spec.rb
> +end
EOFがおかしくなっています。
他のファイルにもあるので確認をお願いします。

2020-12-27 00:11 UTC, kaizumoto commented
レビュアーの伊豆本です。
インラインでコメントしましたのでご確認ください。

2020-12-27 12:46 UTC, kaizumoto commented
レビュアーの伊豆本です。
私からはLGTMです。もう一名のレビューをお待ちください。

2020-12-27 14:55 UTC, codethefuture commented
私からもLGTMです

2020-12-27 16:38 UTC, sugisawakaito commented
{products/:products.id}のURLに飛んだ時に、下部に関連商品が出てくるようにしました。
個数は4つで、その部分から各々の{products/:products.id}のURLに飛べるようになっています。

2020-12-28 03:08 UTC, closed without merging